spring:
  datasource:
    url: jdbc:mysql://47.92.241.17:3306/huiyuan?useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: huiyuan
    password: 2t#svzPYp3RS
    his:
      url: jdbc:mysql://47.92.241.17:3306/meilin_finance?useSSL=false&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: meilin_finance
      password: 2t#svzPYp3RS