spring:
  datasource:
    url: jdbc:mysql://xx.xx.xx.xx:3306/xx?useSSL=false&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xx
    password: xx
    his:
      url: jdbc:mysql://xx.xx.xx.xx:3306/xx?useSSL=false&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: xx
      password: xx